name: Get PR number when merging a PR to main

on:
  push:
    branches:
      - main

jobs:
  pr-data:
    name: Get data for merged PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      data: ${{ steps.get_pr_data.outputs.result }}
    steps:
      - name: Get PR data
        uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            const query = `query($owner: String!, $name: String!, $oid: GitObjectID!) {
                repository(owner: $owner, name: $name) {
                  object(oid: $oid) {
                    ... on Commit {
                      oid
                      message
                      associatedPullRequests(first: 1) {
                        nodes {
                          number
                          title
                          mergedAt
                          mergeCommit {
                            oid
                          }
                        }
                      }
                    }
                  }
                  owner {
                    login
                  }
                  name
                  nameWithOwner
                }
              }`
            const variables = {
                owner: context.repo.owner,
                name: context.repo.repo,
                oid: context.sha,
            }
            const result = await github.graphql(query, variables).then((response) => {
                const res = {
                    pr_number: null,
                    pr_title: null,
                    pr_merged_at: null,
                    pr_merge_commit_sha: null,

                    commit_message: response.repository.object.message,

                    repo_full_name: response.repository.nameWithOwner,
                    repo_owner: response.repository.owner.login,
                    repo_name: response.repository.name,

                    repository: response.repository.nameWithOwner,
                    commitsha: context.sha,
                    commitmessage: response.repository.object.message,
                }

                if (response.repository.object.associatedPullRequests.nodes.length > 0) {
                    const prData = response.repository.object.associatedPullRequests.nodes[0];
                    res.pr_number = prData.number.toString();
                    res.pr_title = prData.title;
                    res.pr_merged_at = prData.mergedAt;
                    res.pr_merge_commit_sha = prData.mergeCommit.oid;
                    res.commitmessage = prData.title;
                }
                return res;
            }).catch((error) => {
                throw error;
            });

            return result;

  print-data:
    name: Print PR data
    runs-on: ubuntu-latest
    needs: pr-data
    steps:
      - name: Dump PR data
        env:
          PR_DATA: ${{ toJson(needs.pr-data.outputs.data) }}
        run: echo "$PR_DATA"
